config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post '/search' => 'home#search', as: 'search'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def search
    @results = Search::Service.new.find({ text: params[:text] })

    render layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
h3.text-center = t('.header')

= form_tag search_path, method: :post, remote: true, class: 'search-form' do
  .input-group
    span.input-group-addon.js-submit-form
      i.glyphicon.glyphicon-search
    = text_field_tag :text, '', class: 'form-control', autocomplete: 'off'

.result-block

app/views/home/search.html.slim
h3 = t('.header')

- unless @results.present?
  h3 = t('.nothing')

- @results.each do |result|
  .panel.panel-primary
    .panel-heading = result[:model]
    .panel-body
      img.img-rounded.pull-left src=result[:image]
      h3 = t('.dimensions')
      = result[:dimensions]

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"

    title Grabber

    /[if lt IE 9]
      script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"
      script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  body
    #waiting-layout
      = image_tag 'wait.gif'
    .container
      = yield
    = javascript_include_tag 'application'